apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mtls
  namespace: openfloat
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: openfloat-core-mtls
  namespace: openfloat
spec:
  host: "openfloat-core-service.openfloat.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: openfloat-auth-mtls
  namespace: openfloat
spec:
  host: "openfloat-auth-service.openfloat.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
