apiVersion: v1
kind: Secret
metadata:
  name: openfloat-secrets
  namespace: openfloat
type: Opaque
stringData:
  POSTGRES_USER: openfloat
  POSTGRES_PASSWORD: change-me
  RABBITMQ_DEFAULT_USER: openfloat
  RABBITMQ_DEFAULT_PASS: change-me
